const $=id=>document.getElementById(id);let db,prompts=[];const BACKUP_VERSION=1;
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open("prompt-manager",1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains("prompts"))r.result.createObjectStore("prompts",{keyPath:"id",autoIncrement:true})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function store(m="readonly"){return db.transaction("prompts",m).objectStore("prompts")}function all(){return req(store().getAll())}function add(x){return req(store("readwrite").add(x))}function del(id){return req(store("readwrite").delete(id))}function req(r){return new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function esc(s=""){return String(s).replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#039;"}[c]))}function name(p){if(p.title)return p.title;let s=p.content.split(/\n/)[0];return s.length>58?s.slice(0,58)+"…":s}function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),1800)}
function applyTheme(v){v==="system"?document.documentElement.removeAttribute("data-theme"):document.documentElement.setAttribute("data-theme",v);localStorage.setItem("pm-theme",v);document.querySelectorAll("[data-theme]").forEach(x=>x.classList.toggle("selected",x.dataset.theme===v))}
function filtered(){let q=$("search").value.trim().toLowerCase();return prompts.filter(p=>!q||(p.title||"").toLowerCase().includes(q)||(p.content||"").toLowerCase().includes(q)||(p.source||"").toLowerCase().includes(q)).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function render(){let xs=filtered(),has=prompts.length>0,q=$("search").value.trim();$("count").textContent=prompts.length;$("empty").hidden=has;$("noresults").hidden=!(has&&q&&!xs.length);$("list").innerHTML=xs.map(p=>`<article class="card"><div class="cardtop"><h4>${esc(name(p))}</h4><button class="more" data-menu="${p.id}" aria-label="More">•••</button></div><div class="preview">${esc(p.content.length>320?p.content.slice(0,320)+"…":p.content)}</div><div class="meta"><span>${new Date(p.createdAt||Date.now()).toLocaleDateString()}</span>${p.source?'<span>Source saved</span>':''}</div><div class="actions"><button class="copy" data-copy="${p.id}">Copy prompt</button>${p.source?`<button data-source="${p.id}">↗ Source</button>`:""}</div><div class="menu" id="menu-${p.id}" hidden><button class="danger" data-delete="${p.id}">Delete prompt</button></div></article>`).join("")}
async function refresh(){prompts=await all();render()}
function fingerprint(p){return `${(p.title||"").trim().toLowerCase()}\u0000${(p.content||"").trim()}\u0000${(p.source||"").trim().toLowerCase()}`}
function exportBackup(){const data={format:"prompt-manager-backup",version:BACKUP_VERSION,exportedAt:new Date().toISOString(),prompts:prompts.map(({id,...p})=>p)};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`prompt-manager-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`${prompts.length} prompt${prompts.length===1?"":"s"} exported`)}
async function restore(file){let data;try{data=JSON.parse(await file.text())}catch{throw new Error("Invalid JSON backup")};if(data?.format!=="prompt-manager-backup"||data.version!==1||!Array.isArray(data.prompts))throw new Error("Unsupported backup");const seen=new Set(prompts.map(fingerprint));let added=0,skipped=0;for(const p of data.prompts){if(!p||typeof p.content!=="string"||!p.content.trim()){skipped++;continue}const clean={title:typeof p.title==="string"?p.title.trim():"",content:p.content.trim(),source:typeof p.source==="string"?p.source.trim():"",createdAt:Number.isFinite(p.createdAt)?p.createdAt:Date.now()},fp=fingerprint(clean);if(seen.has(fp)){skipped++;continue}await add(clean);seen.add(fp);added++}await refresh();return{added,skipped}}
async function init(){applyTheme(localStorage.getItem("pm-theme")||"system");db=await openDB();await refresh();$("search").oninput=render;const openImport=()=>$("dialog").showModal();$("open").onclick=openImport;$("fab").onclick=openImport;$("close").onclick=()=>$("dialog").close();$("backup").onclick=()=>$("backupDialog").showModal();$("backupClose").onclick=()=>$("backupDialog").close();$("theme").onclick=()=>$("themeDialog").showModal();$("themeClose").onclick=()=>$("themeDialog").close();document.querySelector(".theme-options").onclick=e=>{let b=e.target.closest("[data-theme]");if(!b)return;applyTheme(b.dataset.theme);$("themeDialog").close();toast(`${b.dataset.theme[0].toUpperCase()+b.dataset.theme.slice(1)} appearance`)};$("export").onclick=exportBackup;$("importFile").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let r=await restore(f);$("backupDialog").close();toast(`${r.added} restored · ${r.skipped} skipped`)}catch(err){alert(err.message)}finally{e.target.value=""}};$("form").onsubmit=async e=>{e.preventDefault();let content=$("prompt").value.trim();if(!content)return;await add({title:$("title").value.trim(),content,source:$("source").value.trim(),createdAt:Date.now()});e.target.reset();$("dialog").close();await refresh();toast("Prompt saved")};$("list").onclick=async e=>{let m=e.target.closest("[data-menu]");if(m){let el=$(`menu-${m.dataset.menu}`);el.hidden=!el.hidden;return}let id=Number(e.target.dataset.copy||e.target.dataset.source||e.target.dataset.delete);if(!id)return;let p=prompts.find(x=>x.id===id);if(e.target.dataset.copy){await navigator.clipboard.writeText(p.content);toast("Copied to clipboard")}else if(e.target.dataset.source)window.open(p.source,"_blank","noopener");else if(e.target.dataset.delete&&confirm("Delete this prompt?")){await del(id);await refresh();toast("Prompt deleted")}};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error);if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{})}
init().catch(e=>{console.error(e);alert("Prompt Manager could not start.")});
