/* Prompt Manager V2.0.1 — Prompt Chains */
(()=>{"use strict";
const $=id=>document.getElementById(id);
function currentUserId(){try{return authUser?.id||null}catch{return null}}
function draftKey(){const uid=currentUserId();return uid?`pm-chain-draft-v2-${uid}`:"pm-chain-draft-v2-anon"}
let chains=[],loaded=false,loading=false;
const ICON_CHAIN=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9.5 14.5 14.5 9.5"></path><path d="M7.2 16.8 5.8 18.2a3.5 3.5 0 0 1-5-5l3.1-3.1a3.5 3.5 0 0 1 5 0"></path><path d="m16.8 7.2 1.4-1.4a3.5 3.5 0 1 1 5 5l-3.1 3.1a3.5 3.5 0 0 1-5 0"></path></svg>`;
const ICON_COPY=`<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"></rect><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"></path></svg>`;
const ICON_CHEV=`<svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 7.5 5 5 5-5"></path></svg>`;
function lang(){const x=(localStorage.getItem("pm-language")||document.documentElement.lang||"en").toLowerCase();return x.startsWith("es")?"es":x.startsWith("sr")?"sr":"en"}
function tx(){return {
 en:{chain:"CHAIN",steps:"steps",see:"See full chain",hide:"Hide chain",copy:"Copy",copied:"Prompt copied",addChain:"Create chain",addChainSub:"Build a connected sequence of prompts",newChain:"New prompt chain",title:"Chain title",description:"Description",category:"Category",platform:"Platform",model:"Model",step:"Prompt",stepTitle:"Prompt title",prompt:"Prompt",addStep:"Add prompt",fromLibrary:"Add from Library",save:"Save chain",cancel:"Cancel",needTwo:"A chain needs at least 2 prompts",saved:"Chain saved",loadError:"Chains unavailable. Apply the V2.0 SQL migration first.",pick:"Choose a prompt",empty:"No prompts available",delete:"Delete chain",confirmDelete:"Delete this chain?",deleted:"Chain deleted",paste:"Paste",pasted:"Pasted",pasteError:"Clipboard access unavailable"},
 es:{chain:"CADENA",steps:"pasos",see:"Ver cadena completa",hide:"Ocultar cadena",copy:"Copiar",copied:"Prompt copiado",addChain:"Crear cadena",addChainSub:"Crea una secuencia conectada de prompts",newChain:"Nueva cadena de prompts",title:"Título de la cadena",description:"Descripción",category:"Categoría",platform:"Plataforma",model:"Modelo",step:"Prompt",stepTitle:"Título del prompt",prompt:"Prompt",addStep:"Añadir prompt",fromLibrary:"Añadir desde Biblioteca",save:"Guardar cadena",cancel:"Cancelar",needTwo:"Una cadena necesita al menos 2 prompts",saved:"Cadena guardada",loadError:"Las cadenas no están disponibles. Aplica primero la migración SQL V2.0.",pick:"Elige un prompt",empty:"No hay prompts disponibles",delete:"Eliminar cadena",confirmDelete:"¿Eliminar esta cadena?",deleted:"Cadena eliminada",paste:"Pegar",pasted:"Pegado",pasteError:"No se puede acceder al portapapeles"},
 sr:{chain:"LANAC",steps:"koraka",see:"Prikaži ceo lanac",hide:"Sakrij lanac",copy:"Kopiraj",copied:"Prompt kopiran",addChain:"Kreiraj lanac",addChainSub:"Napravi povezani niz promptova",newChain:"Novi lanac promptova",title:"Naziv lanca",description:"Opis",category:"Kategorija",platform:"Platforma",model:"Model",step:"Prompt",stepTitle:"Naziv prompta",prompt:"Prompt",addStep:"Dodaj prompt",fromLibrary:"Dodaj iz Biblioteke",save:"Sačuvaj lanac",cancel:"Otkaži",needTwo:"Lanac mora imati najmanje 2 koraka",saved:"Lanac sačuvan",loadError:"Lanci nisu dostupni. Prvo primeni V2.0 SQL migraciju.",pick:"Izaberi prompt",empty:"Nema dostupnih promptova",delete:"Obriši lanac",confirmDelete:"Obrisati ovaj lanac?",deleted:"Lanac obrisan",paste:"Nalepi",pasted:"Nalepljeno",pasteError:"Pristup clipboard-u nije dostupan"}
 }[lang()]}
function safe(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toastMsg(s){try{toast(s)}catch{const el=$("toast");if(el){el.textContent=s;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}}}
function categoryLabel(id){try{return catName(id||"general")}catch{return id||"General"}}
function platformLabel(id){try{return platformName(id||"general")}catch{return id||"Multiplatform"}}
function cacheKey(){const uid=currentUserId();return uid?`pm-v2-chains-${uid}`:null}
function cacheWrite(){const key=cacheKey();if(!key)return;try{localStorage.setItem(key,JSON.stringify(chains))}catch{}}
function cacheRead(){const key=cacheKey();if(!key)return [];try{const x=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(x)?x:[]}catch{return []}}
async function loadChains(){if(loading)return;loading=true;try{
  let canCloud=false;try{canCloud=!!(supabaseClient&&authUser&&navigator.onLine)}catch{}
  if(canCloud){
    const {data,error}=await supabaseClient.from("prompt_chains").select("*, prompt_chain_steps(*)").order("created_at",{ascending:false});
    if(error)throw error;
    chains=(data||[]).map(c=>({...c,steps:(c.prompt_chain_steps||[]).sort((a,b)=>a.position-b.position)}));cacheWrite();
  }else chains=cacheRead();
  loaded=true;renderChains();
 }catch(err){console.warn("Prompt Chains load failed",err);chains=cacheRead();loaded=true;renderChains();if(!chains.length&&/prompt_chains|schema cache|relation/i.test(String(err?.message||err)))toastMsg(tx().loadError)}finally{loading=false}}
function matchesChain(c){
  let q=$("search")?.value.trim().toLowerCase()||"";
  try{if(activeCategory!=="all"&&String(c.category_id||"general")!==String(activeCategory))return false}catch{}
  try{if(activePlatform!=="any"&&String(c.platform||"general")!==String(activePlatform))return false}catch{}
  try{if(activeOrigin&&activeOrigin!=="all"&&activeOrigin!=="added")return false}catch{}
  if(!q)return true;return [c.title,c.description,c.category_id,c.platform,c.model,...(c.steps||[]).flatMap(s=>[s.title,s.content])].some(v=>String(v||"").toLowerCase().includes(q));
}
function chainCard(c){const t=tx(),steps=c.steps||[],first=steps[0]||{},rest=steps.slice(1),count=steps.length;
 return `<article class="card pm-chain-card" data-chain-id="${safe(c.id)}">
  <div class="pm-chain-rail" aria-hidden="true"><span class="pm-chain-node is-first">01</span><span class="pm-chain-line"></span></div>
  <div class="pm-chain-main">
   <div class="cardtop"><div><div class="badges"><span class="pm-chain-badge">${ICON_CHAIN}${t.chain}</span><span class="categorybadge">${safe(categoryLabel(c.category_id))}</span><span class="platformbadge">${safe(platformLabel(c.platform))}</span>${c.model?`<span class="modelbadge">${safe(c.model)}</span>`:""}<span class="platformbadge">${count} ${t.steps}</span></div><h4>${safe(c.title||"Untitled chain")}</h4></div><button class="more" data-chain-menu="${safe(c.id)}">•••</button></div>
   ${c.description?`<div class="preview pm-chain-description">${safe(c.description)}</div>`:""}
   <section class="pm-chain-first-step"><div><small>${t.step} 1</small><strong>${safe(first.title||`${t.step} 1`)}</strong><p>${safe(first.content||"")}</p></div><button type="button" data-chain-copy="${safe(c.id)}:0">${ICON_COPY}<span>${t.copy}</span></button></section>
   ${rest.length?`<button type="button" class="pm-chain-expand" data-chain-expand="${safe(c.id)}" aria-expanded="false"><span>${t.see}</span>${ICON_CHEV}</button>`:""}
  </div>
  <div class="pm-chain-rest" data-chain-rest="${safe(c.id)}" hidden>${rest.map((s,i)=>`<section class="pm-chain-step" data-chain-step="${i+2}"><span class="pm-chain-node">${String(i+2).padStart(2,"0")}</span><div class="pm-chain-step-body"><div><small>${t.step} ${i+2}</small><strong>${safe(s.title||`${t.step} ${i+2}`)}</strong><p>${safe(s.content||"")}</p></div><button type="button" data-chain-copy="${safe(c.id)}:${i+1}">${ICON_COPY}<span>${t.copy}</span></button></div></section>`).join("")}</div>
  <div class="menu pm-chain-menu" id="chain-menu-${safe(c.id)}" hidden><button class="danger" data-chain-delete="${safe(c.id)}">${t.delete}</button></div>
 </article>`}
function renderChains(){const list=$("list");if(!list||!loaded)return;list.querySelectorAll(".pm-chain-card").forEach(x=>x.remove());const visible=chains.filter(matchesChain);if(!visible.length){updateCount();return}list.insertAdjacentHTML("afterbegin",visible.map(chainCard).join(""));updateCount()}
function updateCount(){const count=$("count");if(!count)return;let base=0;try{base=filtered().length}catch{try{base=prompts.length}catch{}}count.textContent=String(base+chains.filter(matchesChain).length)}
function installRenderHook(){if(typeof render==="function"&&!render.pmChains){const base=render;const wrap=function(){base.apply(this,arguments);renderChains()};wrap.pmChains=true;render=wrap}}
function addChainChoice(){const menu=$("pmAddMenuDialog");if(!menu)return;const options=menu.querySelector(".pm-add-menu-options");if(!options||options.querySelector("[data-pm-add-chain]"))return;const b=document.createElement("button");b.type="button";b.dataset.pmAddChain="";b.innerHTML=`${ICON_CHAIN}<span><strong>${tx().addChain}</strong><small>${tx().addChainSub}</small></span><b>›</b>`;const importButton=options.querySelector("[data-pm-add-import]");if(importButton)options.insertBefore(b,importButton);else options.appendChild(b);b.addEventListener("click",()=>{menu.close();openEditor()})}
function ensureEditor(){let d=$("pmChainDialog");if(d)return d;d=document.createElement("dialog");d.id="pmChainDialog";d.className="pm-chain-dialog";document.body.appendChild(d);d.addEventListener("cancel",e=>{e.preventDefault();draftClear();d.close()});d.addEventListener("input",draftWrite);d.addEventListener("change",draftWrite);d.addEventListener("pointerdown",e=>{if(e.target===d){e.preventDefault();e.stopPropagation()}});d.addEventListener("click",e=>{if(e.target===d){e.preventDefault();e.stopPropagation();return}if(e.target.closest("[data-chain-close]")){draftClear();d.close();return}if(e.target.closest("[data-chain-save]")){saveEditor(e);return}const paste=e.target.closest("[data-chain-paste]");if(paste){pasteIntoPrompt(paste);return}if(e.target.closest("[data-chain-add-step]")){addEditorStep();draftWrite()}if(e.target.closest("[data-chain-from-library]"))openPromptPicker();const rm=e.target.closest("[data-chain-remove-step]");if(rm){rm.closest(".pm-chain-editor-step")?.remove();draftWrite()}});return d}
function draftRead(){try{const x=JSON.parse(localStorage.getItem(draftKey())||"null");return x&&typeof x==="object"?x:null}catch{return null}}
function draftClear(){try{localStorage.removeItem(draftKey())}catch{}}
function draftSnapshot(){const d=$("pmChainDialog");if(!d?.open)return null;return {title:$("pmChainTitle")?.value||"",description:$("pmChainDescription")?.value||"",category:$("pmChainCategory")?.value||"general",platform:$("pmChainPlatform")?.value||"general",model:$("pmChainModel")?.value||"",steps:[...d.querySelectorAll(".pm-chain-editor-step")].map(el=>({title:el.querySelector("[data-step-title]")?.value||"",content:el.querySelector("[data-step-content]")?.value||"",promptId:el.dataset.promptId||""}))}}
function draftWrite(){const x=draftSnapshot();if(!x)return;try{localStorage.setItem(draftKey(),JSON.stringify(x))}catch{}}
async function pasteIntoPrompt(button){const area=button.closest(".pm-chain-prompt-field")?.querySelector("[data-step-content]");if(!area)return;try{const value=await navigator.clipboard.readText();if(value){area.value=value;area.dispatchEvent(new Event("input",{bubbles:true}));toastMsg(tx().pasted)}}catch{toastMsg(tx().pasteError)}}
function modelValuesFor(platform){const registry=window.PM_MODEL_REGISTRY||{};const unique=values=>[...new Set(values.filter(Boolean))];if(!platform||platform==="general"||platform==="other")return unique(Object.values(registry).flat());return unique(registry[platform]||[])}
function syncChainModels({preserve=false}={}){const platform=$("pmChainPlatform"),model=$("pmChainModel");if(!platform||!model)return;const previous=preserve?model.value:"",values=modelValuesFor(platform.value);model.innerHTML=`<option value="">${platform.value==="general"?"Multimodel":"Model"}</option>`+values.map(v=>`<option value="${safe(v)}">${safe(v)}</option>`).join("");if(previous&&values.includes(previous))model.value=previous;else if(platform.value==="general"&&values.includes("Multimodel"))model.value="Multimodel"}
function editorMarkup(){const t=tx(),cats=(()=>{try{return categories}catch{return []}})();
 return `<form id="pmChainForm"><div class="sheethead"><div><small>V2.0 · ${t.chain}</small><h3>${t.newChain}</h3></div><button type="button" class="round" data-chain-close>×</button></div>
 <label>${t.title}<input id="pmChainTitle" maxlength="100" required></label><label>${t.description}<textarea id="pmChainDescription" maxlength="300"></textarea></label>
 <div class="pm-chain-fields"><label>${t.category}<select id="pmChainCategory">${cats.map(c=>`<option value="${safe(c.id)}">${safe(c.name)}</option>`).join("")}</select></label><label>${t.platform}<select id="pmChainPlatform"><option value="general">Multiplatform</option><option value="chatgpt">ChatGPT</option><option value="claude">Claude</option><option value="gemini">Gemini</option><option value="grok">Grok</option><option value="midjourney">Midjourney</option><option value="seedance">Seedance</option><option value="other">Other</option></select></label></div>
 <label>${t.model}<select id="pmChainModel" aria-label="${t.model}"></select></label><div id="pmChainEditorSteps" class="pm-chain-editor-steps"></div>
 <div class="pm-chain-editor-add"><button type="button" data-chain-add-step>＋ ${t.addStep}</button><button type="button" data-chain-from-library>${t.fromLibrary}</button></div><button type="button" class="full primary" data-chain-save>${t.save}</button></form>`}
function openEditor(){const d=ensureEditor();if(d.open){d.focus();return}const draft=draftRead();d.innerHTML=editorMarkup();if(draft?.steps?.length){draft.steps.forEach(s=>addEditorStep(s))}else{addEditorStep();addEditorStep()}if(draft){$("pmChainTitle").value=draft.title||"";$("pmChainDescription").value=draft.description||"";if([...$("pmChainCategory").options].some(o=>o.value===draft.category))$("pmChainCategory").value=draft.category;if([...$("pmChainPlatform").options].some(o=>o.value===draft.platform))$("pmChainPlatform").value=draft.platform}$("pmChainPlatform")?.addEventListener("change",()=>{syncChainModels({preserve:false});draftWrite()});syncChainModels({preserve:false});if(draft?.model&&[...$("pmChainModel").options].some(o=>o.value===draft.model))$("pmChainModel").value=draft.model;d.showModal();requestAnimationFrame(()=>{d.scrollTop=0;d.querySelector("form")?.scrollTo?.(0,0);draftWrite()})}
function addEditorStep(data={}){const wrap=$("pmChainEditorSteps");if(!wrap)return;const n=wrap.children.length+1,t=tx(),el=document.createElement("section");el.className="pm-chain-editor-step";el.dataset.promptId=data.promptId||"";el.innerHTML=`<div class="pm-chain-editor-step-head"><b>${String(n).padStart(2,"0")}</b><strong>${t.step} ${n}</strong>${n>2?'<button type="button" data-chain-remove-step aria-label="Remove step">×</button>':""}</div><label>${t.stepTitle}<input data-step-title maxlength="100" value="${safe(data.title||"")}"></label><label class="pm-chain-prompt-field"><span class="pm-chain-prompt-label">${t.prompt}<button type="button" data-chain-paste>${t.paste}</button></span><textarea data-step-content required>${safe(data.content||"")}</textarea></label>`;wrap.appendChild(el);el.scrollIntoView({block:"nearest",behavior:"smooth"})}
function openPromptPicker(){let d=$("pmChainPicker");if(!d){d=document.createElement("dialog");d.id="pmChainPicker";d.className="sheet pm-chain-picker";document.body.appendChild(d)}const t=tx(),ps=(()=>{try{return prompts}catch{return []}})();d.innerHTML=`<div class="sheethead"><div><small>LIBRARY</small><h3>${t.pick}</h3></div><button type="button" class="x" data-picker-close>×</button></div><div class="pm-chain-picker-list">${ps.length?ps.map(p=>`<button type="button" data-picker-prompt="${safe(p.id)}"><strong>${safe(p.title||"Untitled")}</strong><small>${safe(String(p.content||"").slice(0,120))}</small></button>`).join(""):`<p class="hint">${t.empty}</p>`}</div>`;d.onclick=e=>{if(e.target.closest("[data-picker-close]")){d.close();return}const b=e.target.closest("[data-picker-prompt]");if(!b)return;const p=ps.find(x=>String(x.id)===String(b.dataset.pickerPrompt));if(p){addEditorStep({title:p.title,content:p.content,promptId:p.cloudId||""});d.close()}};d.showModal()}
async function saveEditor(e){e?.preventDefault?.();const d=$("pmChainDialog"),form=$("pmChainForm"),t=tx();if(!form||form.dataset.saving==="1")return;const title=$("pmChainTitle")?.value.trim()||"";if(!title){$("pmChainTitle")?.focus();toastMsg("Add a chain title");return}form.dataset.saving="1";const saveButton=form.querySelector("[data-chain-save]");if(saveButton)saveButton.disabled=true;const stepEls=[...d.querySelectorAll(".pm-chain-editor-step")],steps=stepEls.map((el,i)=>({position:i+1,title:el.querySelector("[data-step-title]").value.trim()||`${t.step} ${i+1}`,content:el.querySelector("[data-step-content]").value.trim(),prompt_id:el.dataset.promptId||null})).filter(s=>s.content);if(steps.length<2){toastMsg(t.needTwo);form.dataset.saving="";if(saveButton)saveButton.disabled=false;return}let user=null;try{user=authUser}catch{}if(!user){toastMsg("Sign in required");form.dataset.saving="";if(saveButton)saveButton.disabled=false;return}const chain={user_id:user.id,title,description:$("pmChainDescription").value.trim(),category_id:$("pmChainCategory").value||"general",platform:$("pmChainPlatform").value||"general",model:$("pmChainModel").value||null};try{const {data,error}=await supabaseClient.from("prompt_chains").insert(chain).select().single();if(error)throw error;const rows=steps.map(s=>({...s,chain_id:data.id,user_id:user.id}));const {error:se}=await supabaseClient.from("prompt_chain_steps").insert(rows);if(se){await supabaseClient.from("prompt_chains").delete().eq("id",data.id);throw se}draftClear();d.close();await loadChains();toastMsg(t.saved)}catch(err){console.error("Save chain failed",err);form.dataset.saving="";if(saveButton)saveButton.disabled=false;toastMsg(`Save failed: ${err?.message||"Unknown error"}`)}}
async function deleteChain(id){if(!confirm(tx().confirmDelete))return;try{const {error}=await supabaseClient.from("prompt_chains").delete().eq("id",id);if(error)throw error;chains=chains.filter(c=>String(c.id)!==String(id));cacheWrite();renderChains();toastMsg(tx().deleted)}catch(err){console.error(err);toastMsg(tx().loadError)}}
function clickHandler(e){const exp=e.target.closest("[data-chain-expand]");if(exp){const id=exp.dataset.chainExpand,rest=document.querySelector(`[data-chain-rest="${CSS.escape(id)}"]`),open=exp.getAttribute("aria-expanded")!=="true";exp.setAttribute("aria-expanded",String(open));exp.querySelector("span").textContent=open?tx().hide:tx().see;if(rest)rest.hidden=!open;return}const cp=e.target.closest("[data-chain-copy]");if(cp){const [id,idx]=cp.dataset.chainCopy.split(":");const c=chains.find(x=>String(x.id)===id),s=c?.steps?.[Number(idx)];if(s?.content)navigator.clipboard.writeText(s.content).then(()=>toastMsg(tx().copied));return}const menu=e.target.closest("[data-chain-menu]");if(menu){e.stopPropagation();const m=$("chain-menu-"+menu.dataset.chainMenu);if(m)m.hidden=!m.hidden;return}const del=e.target.closest("[data-chain-delete]");if(del){deleteChain(del.dataset.chainDelete);return}}
function observeAddMenu(){addChainChoice();new MutationObserver(addChainChoice).observe(document.body,{childList:true,subtree:true})}
function saveDraftOnLifecycle(){if($("pmChainDialog")?.open)draftWrite()}
function init(){window.addEventListener("pagehide",saveDraftOnLifecycle);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden")saveDraftOnLifecycle()});window.pmOpenChainEditor=openEditor;window.addEventListener("pm:create-chain",openEditor);installRenderHook();observeAddMenu();$("list")?.addEventListener("click",clickHandler);$("search")?.addEventListener("input",()=>setTimeout(renderChains,0));$("categoryFilters")?.addEventListener("click",()=>setTimeout(renderChains,0));$("platformOptions")?.addEventListener("click",()=>setTimeout(renderChains,0));$("libraryOriginFilters")?.addEventListener("click",()=>setTimeout(renderChains,0));document.addEventListener("change",e=>{if(e.target?.id==="pmLanguageSelect")setTimeout(()=>{renderChains();addChainChoice()},0)},true);loadChains()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
