(()=>{"use strict";const M=500;let rows=[],heads=[],map={},file=null;const q=id=>document.getElementById(id),n=s=>String(s??"").trim(),k=s=>n(s).toLowerCase().replace(/[\s_-]+/g,""),eh=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function reset(){rows=[];heads=[];map={};file=null;q("bulkImportFile").value="";q("importPick").hidden=false;q("importPreview").hidden=true;q("importResult").hidden=true}
function csv(t){let a=[],r=[],f="",z=false;for(let i=0;i<t.length;i++){let c=t[i],d=t[i+1];if(z){if(c=='"'&&d=='"'){f+='"';i++}else if(c=='"')z=false;else f+=c}else if(c=='"')z=true;else if(c==","){r.push(f);f=""}else if(c=="\n"){r.push(f);a.push(r);r=[];f=""}else if(c!="\r")f+=c}r.push(f);if(r.some(n))a.push(r);return a}
function fromCSV(t){let a=csv(t);if(!a.length)return[];let known=["prompt","content","text","title","name","category","platform","source","url"],hdr=a[0].some(x=>known.includes(k(x)));heads=hdr?a[0].map((x,i)=>n(x)||`Column ${i+1}`):a[0].map((_,i)=>`Column ${i+1}`);return(hdr?a.slice(1):a).filter(r=>r.some(n)).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??""])))}
function fromJSON(t){let x=JSON.parse(t),a=Array.isArray(x)?x:Array.isArray(x.prompts)?x.prompts:[x];if(a.every(x=>typeof x=="string")){heads=["prompt"];return a.map(prompt=>({prompt}))}a=a.filter(x=>x&&typeof x=="object"&&!Array.isArray(x));heads=[...new Set(a.flatMap(Object.keys))];return a}
function automap(){let A={prompt:["prompt","content","text","instruction","instructions"],title:["title","name"],category:["category","type","topic"],platform:["platform","platforms","model","tool"],source:["sourceurl","source","url","link"]};map={};for(let [f,as]of Object.entries(A)){let h=heads.find(x=>as.includes(k(x)));if(h)map[f]=h}if(!map.prompt&&heads.length==1)map.prompt=heads[0]}
const val=(o,f)=>n(map[f]?o[map[f]]:"");
function title(p,i){let s=p.replace(/\s+/g," ").split(/[.!?\n]/)[0].replace(/^(please|act as|you are|create|write|generate)\s+/i,"").trim();return(s.split(/\s+/).slice(0,8).join(" ")||`Imported Prompt ${i+1}`).slice(0,80)}
function cat(p){let t=p.toLowerCase(),R=[["Coding",/\b(code|developer|javascript|python|typescript|sql|api|debug)\b/],["Marketing",/\b(marketing|linkedin|seo|campaign|brand|sales|copywriting)\b/],["Writing",/\b(write|writing|article|blog|email|story|rewrite)\b/],["Image",/\b(image|photo|midjourney|visual|portrait|illustration)\b/],["Video",/\b(video|cinematic|film|storyboard)\b/],["Research",/\b(research|analy[sz]e|study|investigate|compare)\b/],["Productivity",/\b(productivity|plan|schedule|workflow|organize|task)\b/]];return R.find(x=>x[1].test(t))?.[0]||"General"}
function platform(x){x=x.toLowerCase();return["chatgpt","claude","gemini","grok","midjourney"].find(p=>x.includes(p))||"general"}
function normalized(){let old=new Set;try{for(let p of prompts||[])old.add(n(p.content).toLowerCase().replace(/\s+/g," "))}catch{}let seen=new Set;return rows.map((o,i)=>{let content=val(o,"prompt"),sig=content.toLowerCase().replace(/\s+/g," "),dup=!!content&&(old.has(sig)||seen.has(sig));if(content)seen.add(sig);return{valid:!!content,dup,title:val(o,"title")||title(content,i),content,category:val(o,"category")||cat(content),platform:platform(val(o,"platform")),source:val(o,"source")}})}
function mapping(){let F=[["prompt","Prompt text *"],["title","Title"],["category","Category"],["platform","Platform"],["source","Source URL"]];q("importMapping").innerHTML=F.map(([f,l])=>`<label class="pm-import-field"><span>${l}</span><select data-map="${f}"><option value="">${f=="prompt"?"Select column":"Auto / none"}</option>${heads.map(h=>`<option value="${eh(h)}"${map[f]==h?" selected":""}>${eh(h)}</option>`).join("")}</select></label>`).join("")}
function preview(){let a=normalized(),ok=a.filter(x=>x.valid&&!x.dup),du=a.filter(x=>x.dup).length,bad=a.filter(x=>!x.valid).length;q("importCount").textContent=`${rows.length} prompt${rows.length==1?"":"s"} detected`;q("importName").textContent=file?.name||"";q("importRows").innerHTML=a.slice(0,30).map(x=>`<div class="pm-import-row" data-state="${x.dup?"duplicate":x.valid?"ready":"error"}"><div><strong>${eh(x.title||"Untitled")}</strong><small>${eh(x.content||"Missing prompt text")}</small></div><em>${x.dup?"Duplicate":x.valid?eh(x.category):"Error"}</em></div>`).join("");q("importHint").textContent=`${ok.length} ready${du?` · ${du} duplicate${du==1?"":"s"} skipped`:""}${bad?` · ${bad} error${bad==1?"":"s"}`:""}.`;q("importConfirm").disabled=!map.prompt||!ok.length}
async function load(f){if(!f)return;if(f.size>5e6){toast("Maximum file size is 5 MB");return}try{let t=await f.text();rows=f.name.toLowerCase().endsWith(".json")?fromJSON(t):fromCSV(t);if(!rows.length)throw Error("No prompts found");if(rows.length>M)throw Error(`Maximum is ${M} prompts per file`);file=f;automap();q("importPick").hidden=true;q("importPreview").hidden=false;mapping();preview()}catch(e){console.error(e);toast(e.message||"Could not read file")}}
async function run(){let a=normalized().filter(x=>x.valid&&!x.dup),b=q("importConfirm"),done=0,fail=0;b.disabled=true;b.textContent="Importing…";for(let x of a)try{let cid="general";try{cid=(categories||[]).find(c=>String(c.name||c.id).toLowerCase()==x.category.toLowerCase())?.id||slug(x.category)||"general"}catch{}await add("prompts",{title:x.title,content:x.content,source:x.source,categoryId:cid,createdAt:Date.now(),platforms:[x.platform],useCount:0,lastUsedAt:null,acquisitionType:"manual",sourceName:"Bulk import",externalId:null});done++}catch(e){console.error(e);fail++}await refresh();q("importPreview").hidden=true;q("importResult").hidden=false;q("importResultText").textContent=`${done} imported${rows.length-done-fail?` · ${rows.length-done-fail} skipped`:""}${fail?` · ${fail} failed`:""}.`;b.disabled=false;b.textContent="Import to Library"}
q("openBulkImport")?.addEventListener("click",()=>{reset();q("settingsDialog")?.close();q("profileMenu")?.close();q("bulkImportDialog")?.showModal()});q("bulkImportClose")?.addEventListener("click",()=>q("bulkImportDialog").close());q("importDone")?.addEventListener("click",()=>q("bulkImportDialog").close());q("importReset")?.addEventListener("click",reset);q("bulkImportFile")?.addEventListener("change",e=>load(e.target.files?.[0]));q("importMapping")?.addEventListener("change",e=>{if(e.target?.dataset?.map){map[e.target.dataset.map]=e.target.value;preview()}});q("importConfirm")?.addEventListener("click",run)})();